server:
  port: 8088
  error:
    include-exception: false
    include-stacktrace: never # 오류 응답에 stacktrace 내용을 포함할 지 여부

spring:
  profiles:
    group:
      "local": "local,common"
      "dev": "dev,common"
      "prod": "prod,common"

---
# 로컬 개발 환경
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/dpcms
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true # ??? ??? ??
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.H2Dialect

    open-in-view: false # OSIV 설정

---
# 개발 환경
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/dpcms
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql: true # ??? ??? ??
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.H2Dialect

    open-in-view: false # OSIV 설정

---
# ??
spring:
  config:
    activate:
      on-profile: "common"
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    restart:
      enabled: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: debug # ??? ??


Globals:
  rootPath: /Users/kimgunwoo/IdeaProjects/cms/src/main/webapp
  AesSecretKey: dpcmsV1AesSecret
  fileStorePath: /Users/kimgunwoo/IdeaProjects/cms/src/main/webapp/upload


#  org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6


# Spring Security
security:
  ## ?? ???
  session:
    use: true
    ### ?? ?? ???
    max-count: 1

  ## ?? ???
  remember-me:
    use: false
    ### ????? ????(n? ?? ??)
    expire:
      seconds: 2629800

  ## ???? ??
  credentials-expired:
    use: true
    ### ???? ?? ? ????? uri
    redirect: /credentialExpired
    ### ???? ???? (?,?)
    month: 1
    data:

  ## ????
  signup:
    uri: /signup
    process:
      uri: /signupProcess

  ## ???
  login:
    uri: /admin/ad/loginPage
    ### form ????
    param:
      id: memberId
      pwd: memberPassword
    process:
      uri: /admin/ad/login
    ### ??? ?? ? ????? uri
    success:
      redirect-uri: /
    fail:
      imsi-lock: # ???? ???? ?? ??
        use: true
        recount:
          use: true
          # ?? ?? ??
          max-minute: 1
          # ?? ?? ??
        max-count: 5
        # ???? ?? ?? ? ??? ??? ??
        lock-minute: 30
      redirect-uri:
        default: ${security.login.uri}?error=true
        notApprove:
        inactive:
        userNotFound:
        badCredentials:
  ## ????
  logout:
    uri: /logout
  permitAll: >
    ${security.login.uri},
    ${security.login.process.uri},
    ${security.signup.uri},
    ${security.signup.process.uri}





